# PBS configuration
# If submitting to a different project to your default uncomment line below 
# and change project code as appropriate
project: e14
queue: normal
walltime: 5:00:00
jobname: 01deg_nostress
ncpus: 5180

# Force payu to always find, and save, files in this short (or scratch) project directory
shortpath: /scratch/e14

# Model configuration
name: common
model: access-om2
input: /g/data/ik11/inputs/access-om2/input_08022019/common_01deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /g/data/ik11/inputs/access-om2/bin/yatm_1bb8904.exe
      input: /g/data/ik11/inputs/access-om2/input_08022019/yatm_01deg
      ncpus: 1

    - name: ocean
      model: mom
#      exe: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM_97e3429_libaccessom2_1bb8904.x
      exe: /g/data/e14/rmh561/access-om2/bin/fms_ACCESS-OM_ce6567d_libaccessom2_1bb8904.x
      input: /g/data/ik11/inputs/access-om2/input_08022019/mom_01deg
      ncpus: 4358

    - name: ice
      model: cice5
      exe: /g/data/ik11/inputs/access-om2/bin/cice_auscom_3600x2700_722p_d3e8bdf_libaccessom2_1bb8904.exe
      input: /g/data/ik11/inputs/access-om2/input_08022019/cice_01deg
      ncpus: 799

# Collation
collate:
  mpi: true
  walltime: 1:00:00
  mem: 16GB
  ncpus: 4
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine-fast

# Misc
runlog: true
stacksize: unlimited
restart_freq: 1  # use tidy_restarts.py instead
###mpirun: -mca coll_hcoll_enable 1  ##--mca pml yalla -x MXM_LOG_FILE=$PBS_JOBFS/mxm.log
qsub_flags: -W umask=027 
storage:
      gdata:
          - ua8
          - e14
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48

# DANGER! Do not uncomment this without checking the script is synching 
# to the correct location!
# postscript: sync_output_to_gdata.sh
